name: music_kit_platform_interface
description: A common platform interface for the music_kit plugin.
version: 1.1.0
homepage: https://github.com/misiio/flutter_music_kit/tree/master/music_kit_platform_interface

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
