name: music_kit
description: A Flutter plugin to access and play Apple Music.
version: 1.0.0
homepage: https://github.com/misiio/flutter_music_kit/tree/master/music_kit

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  music_kit_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  plugin:
    platforms:
      android:
        package: app.misi.music_kit
        pluginClass: MusicKitPlugin
      ios:
        pluginClass: MusicKitPlugin
